name: CLA check

on:
  pull_request:
    branches: [main]

jobs:
  cla-check:
    runs-on: ubuntu-24.04
    steps:
      - name: Check if Canonical's Contributor License Agreement has been signed
        uses: canonical/has-signed-canonical-cla@5d1443b94417bd150ad234a82fe21f7340a25e4d # v2
